-- This migration was an accidental artifact from `prisma generate`.
-- It attempted to drop/redefine objects that are introduced in later migrations,
-- which breaks fresh `migrate deploy` runs (e.g. template DB creation in CI).
-- Intentionally left as a no-op for migration history compatibility.
